name: Validate workflows

on:
  push:
    branches:
      - main
  pull_request:
    
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 20
      - name: Validate workflows
        run: |
          npm ci
          npx ts-node-script ./index.ts
        working-directory: 
          ./script/validate
