
on:
  workflow_call:
    inputs:
      envPath:
        description: "Which env to target (staging/production)"
        required: true
        type: string
      csp_access_key_id_env_var:
        description: "CSP env name used to authenticate"
        required: true
        type: string
      csp_access_key_env_var:
        description: "CSP env name used to authenticate"
        required: true
        type: string
      csp_region:
        description: "CSP region env name"
        required: true
        type: string
      region:
        description: "CSP region to deploy to"
        required: true
        type: string
    secrets:
      csp_access_key_id:
        description: "Access key id used to authenticate"
        required: true
      csp_access_key:
        description: "Access key used to authenticate"
        required: true
  workflow_dispatch:
    inputs:
      envPath:
        description: "Which env to target (staging/production)"
        required: true
        type: string
      csp_access_key_id_env_var:
        description: "CSP env name used to authenticate"
        required: true
        type: string
      csp_access_key_env_var:
        description: "CSP env name used to authenticate"
        required: true
        type: string
      csp_region:
        description: "CSP region env name"
        required: true
        type: string
      region:
        description: "CSP region to deploy to"
        required: true
        type: string
    secrets:
      csp_access_key_id:
        description: "Access key id used to authenticate"
        required: true
      csp_access_key:
        description: "Access key used to authenticate"
        required: true


jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:1.0.11

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Download plan
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.envPath }}-plan
          path: ${{ inputs.envPath }}

      - name: Run terraform apply
        env:
          ${{ inputs.csp_access_key_id_env_var}}: ${{ secrets.csp_access_key_id }}
          ${{ inputs.csp_access_key_env_var}}: ${{ secrets.csp_access_key }}
          ${{ inputs.csp_region}}: ${{ inputs.region }}
        run: |
             cd ${{ inputs.envPath }}
             terraform init
             terraform apply -auto-approve "${{ inputs.envPath }}-plan"
