on:
  workflow_call:
    inputs:
      envPath:
        description: "Which env to target (staging/production)"
        required: true
        type: string
      csp_access_key_id_env_var:
        description: "CSP env name used to authenticate"
        required: false
        type: string
      csp_access_key_env_var:
        description: "CSP env name used to authenticate"
        required: false
        type: string
      csp_region:
        description: "CSP region env name"
        required: false
        type: string
      region:
        description: "CSP region to deploy to"
        required: false
        type: string
    secrets:
      csp_access_key_id:
        description: "Access key id used to authenticate"
        required: false
      csp_access_key:
        description: "Access key used to authenticate"
        required: false


jobs:
  checkov_scan:
    runs-on: ubuntu-latest
    container:
      image: bridgecrew/checkov:2
    if: always()

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run checkov scan on ${{ inputs.envPath }}
        run: checkov -d ${{ inputs.envPath }}

  terraform_validate:
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:1.0.11

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run terraform validate
        env:
          ${{ inputs.csp_access_key_id_env_var}}: ${{ secrets.csp_access_key_id }}
          ${{ inputs.csp_access_key_env_var}}: ${{ secrets.csp_access_key }}
          ${{ inputs.csp_region}}: ${{ inputs.region }}
        run: |
             cd ${{ inputs.envPath }}
             terraform init
             terraform validate
