on:
  workflow_call:
    inputs:
      envPath:
        description: "Which env to target (staging/production)"
        required: true
        type: string
      planName:
        description: "Plan name"
        required: true
        type: string
      csp_iam_account_id_env_name:
        description: "Name of env name to provide iam account id"
        required: true
        type: string
      csp_iam_account_secret_env_name:
        description: "Name of env name to provide iam account secret"
        required: true
        type: string
      csp_region_env_name:
        description: "CSP region env name"
        required: true
        type: string
      region:
        description: "CSP region to deploy to"
        required: true
        type: string
      runner:
        description: "Env of runner (staging/production)"
        required: false
        type: string
        default: ubuntu-latest
    secrets:
      iam_account_id:
        description: "Account id used to authenticate"
        required: true
      iam_account_secret:
        description: "Account password used to authenticate"
        required: true

jobs:

  plan:
    # runs-on: ubuntu-latest
    runs-on: ${{ inputs.runner }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run terraform plan
        env:
          ${{ inputs.csp_iam_account_id_env_name }}: ${{ secrets.iam_account_id }}
          ${{ inputs.csp_iam_account_secret_env_name }}: ${{ secrets.iam_account_secret }}
          ${{ inputs.csp_region_env_name }}: ${{ inputs.region }}
        run: |
             cd ${{ inputs.envPath }}
             terraform init
             terraform plan -out=${{ inputs.planName }}

      - name: 'Upload Plan'
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.planName }}
          path: ${{ inputs.envPath }}/${{ inputs.planName }}
          retention-days: 1
